//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaSanPham
    {
        public int MaDanhGia { get; set; }
        public int MaKH { get; set; }
        public int MaDia { get; set; }
        public int DiemDanhGia { get; set; }
        public string BinhLuan { get; set; }
        public System.DateTime NgayDanhGia { get; set; }
    
        public virtual DiaPhimCaNhac DiaPhimCaNhac { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
