//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiaPhimCaNhac
    {
        public DiaPhimCaNhac()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.DanhGiaSanPhams = new HashSet<DanhGiaSanPham>();
            this.GioHangs = new HashSet<GioHang>();
            this.KhuyenMais = new HashSet<KhuyenMai>();
            this.ThamGiaThucHiens = new HashSet<ThamGiaThucHien>();
        }
    
        public int MaDia { get; set; }
        public string TenDia { get; set; }
        public decimal GiaBan { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public string AnhBia { get; set; }
        public int SoLuongTon { get; set; }
        public Nullable<int> ThoiLuong { get; set; }
        public string ChatLuong { get; set; }
        public string NgonNgu { get; set; }
        public int MaLoaiDia { get; set; }
        public int MaNhaSanXuat { get; set; }
        public bool LaDiaPhim { get; set; }
        public Nullable<decimal> DanhGia { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public bool TrangThai { get; set; }
        public bool LaSanPhamNoiBat { get; set; }
        public Nullable<int> MaNguoiBan { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual ICollection<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual LoaiDia LoaiDia { get; set; }
        public virtual NguoiBan NguoiBan { get; set; }
        public virtual NhaSanXuat NhaSanXuat { get; set; }
        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
        public virtual ICollection<ThamGiaThucHien> ThamGiaThucHiens { get; set; }
    }
}
