//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.GiaoDichThanhToans = new HashSet<GiaoDichThanhToan>();
        }
    
        public int MaDonHang { get; set; }
        public System.DateTime NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
        public decimal TongTien { get; set; }
        public bool DaThanhToan { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public int TinhTrangGiaoHang { get; set; }
        public string DiaChiGiao { get; set; }
        public string GhiChu { get; set; }
        public int MaKH { get; set; }
        public Nullable<int> MaNguoiBan { get; set; }
    
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual NguoiBan NguoiBan { get; set; }
        public virtual TrangThaiGiaoHang TrangThaiGiaoHang { get; set; }
        public virtual ICollection<GiaoDichThanhToan> GiaoDichThanhToans { get; set; }
    }
}
