//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoDichThanhToan
    {
        public int MaGiaoDich { get; set; }
        public int MaDonHang { get; set; }
        public string MaThanhToan { get; set; }
        public Nullable<System.DateTime> NgayThanhToan { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string TrangThai { get; set; }
    
        public virtual DonHang DonHang { get; set; }
    }
}
