//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {
        public int MaKhuyenMai { get; set; }
        public string TenKhuyenMai { get; set; }
        public string MoTa { get; set; }
        public Nullable<decimal> GiaGiam { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<int> MaDia { get; set; }
        public Nullable<int> MaNguoiBan { get; set; }
    
        public virtual DiaPhimCaNhac DiaPhimCaNhac { get; set; }
        public virtual NguoiBan NguoiBan { get; set; }
    }
}
