//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDia
    {
        public LoaiDia()
        {
            this.DiaPhimCaNhacs = new HashSet<DiaPhimCaNhac>();
        }
    
        public int MaLoaiDia { get; set; }
        public string TenLoaiDia { get; set; }
        public string MoTa { get; set; }
    
        public virtual ICollection<DiaPhimCaNhac> DiaPhimCaNhacs { get; set; }
    }
}
