//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiBan
    {
        public NguoiBan()
        {
            this.DiaPhimCaNhacs = new HashSet<DiaPhimCaNhac>();
            this.DonHangs = new HashSet<DonHang>();
            this.KhuyenMais = new HashSet<KhuyenMai>();
        }
    
        public int MaNguoiBan { get; set; }
        public string HoTen { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual ICollection<DiaPhimCaNhac> DiaPhimCaNhacs { get; set; }
        public virtual ICollection<DonHang> DonHangs { get; set; }
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
    }
}
