//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaSanXuat
    {
        public NhaSanXuat()
        {
            this.DiaPhimCaNhacs = new HashSet<DiaPhimCaNhac>();
        }
    
        public int MaNhaSanXuat { get; set; }
        public string TenNhaSanXuat { get; set; }
        public string DiaChi { get; set; }
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    
        public virtual ICollection<DiaPhimCaNhac> DiaPhimCaNhacs { get; set; }
    }
}
