//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QuanLyDiaPhimCaNhac_EditedEntities : DbContext
    {
        public QuanLyDiaPhimCaNhac_EditedEntities()
            : base("name=QuanLyDiaPhimCaNhac_EditedEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual DbSet<DanhGiaSanPham> DanhGiaSanPhams { get; set; }
        public virtual DbSet<DiaPhimCaNhac> DiaPhimCaNhacs { get; set; }
        public virtual DbSet<DonHang> DonHangs { get; set; }
        public virtual DbSet<GiaoDichThanhToan> GiaoDichThanhToans { get; set; }
        public virtual DbSet<GioHang> GioHangs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<KhuyenMai> KhuyenMais { get; set; }
        public virtual DbSet<LoaiDia> LoaiDias { get; set; }
        public virtual DbSet<NgheSi> NgheSis { get; set; }
        public virtual DbSet<NguoiBan> NguoiBans { get; set; }
        public virtual DbSet<NhaSanXuat> NhaSanXuats { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThamGiaThucHien> ThamGiaThucHiens { get; set; }
        public virtual DbSet<TrangThaiGiaoHang> TrangThaiGiaoHangs { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_GetChiTietDiaPhimCaNhac_Result> sp_GetChiTietDiaPhimCaNhac(Nullable<int> maDia)
        {
            var maDiaParameter = maDia.HasValue ?
                new ObjectParameter("MaDia", maDia) :
                new ObjectParameter("MaDia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetChiTietDiaPhimCaNhac_Result>("sp_GetChiTietDiaPhimCaNhac", maDiaParameter);
        }
    
        public virtual ObjectResult<sp_GetDiaPhimCaNhacByLoai_Result> sp_GetDiaPhimCaNhacByLoai(Nullable<int> maLoaiDia, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var maLoaiDiaParameter = maLoaiDia.HasValue ?
                new ObjectParameter("MaLoaiDia", maLoaiDia) :
                new ObjectParameter("MaLoaiDia", typeof(int));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDiaPhimCaNhacByLoai_Result>("sp_GetDiaPhimCaNhacByLoai", maLoaiDiaParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<sp_GetDiaPhimCaNhacByLoaiAndPrice_Result> sp_GetDiaPhimCaNhacByLoaiAndPrice(Nullable<int> maLoaiDia, Nullable<decimal> minPrice, Nullable<decimal> maxPrice, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var maLoaiDiaParameter = maLoaiDia.HasValue ?
                new ObjectParameter("MaLoaiDia", maLoaiDia) :
                new ObjectParameter("MaLoaiDia", typeof(int));
    
            var minPriceParameter = minPrice.HasValue ?
                new ObjectParameter("MinPrice", minPrice) :
                new ObjectParameter("MinPrice", typeof(decimal));
    
            var maxPriceParameter = maxPrice.HasValue ?
                new ObjectParameter("MaxPrice", maxPrice) :
                new ObjectParameter("MaxPrice", typeof(decimal));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDiaPhimCaNhacByLoaiAndPrice_Result>("sp_GetDiaPhimCaNhacByLoaiAndPrice", maLoaiDiaParameter, minPriceParameter, maxPriceParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<sp_GetDiaPhimCaNhacByPrice_Result> sp_GetDiaPhimCaNhacByPrice(Nullable<decimal> minPrice, Nullable<decimal> maxPrice, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var minPriceParameter = minPrice.HasValue ?
                new ObjectParameter("MinPrice", minPrice) :
                new ObjectParameter("MinPrice", typeof(decimal));
    
            var maxPriceParameter = maxPrice.HasValue ?
                new ObjectParameter("MaxPrice", maxPrice) :
                new ObjectParameter("MaxPrice", typeof(decimal));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetDiaPhimCaNhacByPrice_Result>("sp_GetDiaPhimCaNhacByPrice", minPriceParameter, maxPriceParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<sp_GetLoaiDia_Result> sp_GetLoaiDia(Nullable<bool> laDiaPhim)
        {
            var laDiaPhimParameter = laDiaPhim.HasValue ?
                new ObjectParameter("LaDiaPhim", laDiaPhim) :
                new ObjectParameter("LaDiaPhim", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLoaiDia_Result>("sp_GetLoaiDia", laDiaPhimParameter);
        }
    
        public virtual ObjectResult<sp_GetLoaiDiaWithCount_Result> sp_GetLoaiDiaWithCount(Nullable<bool> laDiaPhim)
        {
            var laDiaPhimParameter = laDiaPhim.HasValue ?
                new ObjectParameter("LaDiaPhim", laDiaPhim) :
                new ObjectParameter("LaDiaPhim", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetLoaiDiaWithCount_Result>("sp_GetLoaiDiaWithCount", laDiaPhimParameter);
        }
    
        public virtual ObjectResult<sp_GetSanPhamNoiBat_Result> sp_GetSanPhamNoiBat(Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetSanPhamNoiBat_Result>("sp_GetSanPhamNoiBat", pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_SearchDiaPhimCaNhac_Result> sp_SearchDiaPhimCaNhac(string searchText, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var searchTextParameter = searchText != null ?
                new ObjectParameter("SearchText", searchText) :
                new ObjectParameter("SearchText", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_SearchDiaPhimCaNhac_Result>("sp_SearchDiaPhimCaNhac", searchTextParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_TaoDonHang(Nullable<int> maKH, string diaChiGiao, string ghiChu, string phuongThucThanhToan)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var diaChiGiaoParameter = diaChiGiao != null ?
                new ObjectParameter("DiaChiGiao", diaChiGiao) :
                new ObjectParameter("DiaChiGiao", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var phuongThucThanhToanParameter = phuongThucThanhToan != null ?
                new ObjectParameter("PhuongThucThanhToan", phuongThucThanhToan) :
                new ObjectParameter("PhuongThucThanhToan", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_TaoDonHang", maKHParameter, diaChiGiaoParameter, ghiChuParameter, phuongThucThanhToanParameter);
        }
    
        public virtual int sp_ThemVaoGioHang(Nullable<int> maKH, Nullable<int> maDia, Nullable<int> soLuong)
        {
            var maKHParameter = maKH.HasValue ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(int));
    
            var maDiaParameter = maDia.HasValue ?
                new ObjectParameter("MaDia", maDia) :
                new ObjectParameter("MaDia", typeof(int));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemVaoGioHang", maKHParameter, maDiaParameter, soLuongParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
