//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamGiaThucHien
    {
        public int MaDia { get; set; }
        public int MaNgheSi { get; set; }
        public string VaiTro { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DiaPhimCaNhac DiaPhimCaNhac { get; set; }
        public virtual NgheSi NgheSi { get; set; }
    }
}
