//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnQuanLyQuangCaoDiaPhimCaNhac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrangThaiGiaoHang
    {
        public TrangThaiGiaoHang()
        {
            this.DonHangs = new HashSet<DonHang>();
        }
    
        public int MaTrangThai { get; set; }
        public string TenTrangThai { get; set; }
    
        public virtual ICollection<DonHang> DonHangs { get; set; }
    }
}
